/**
 * Country database: canonical name, centroid coordinates, and aliases.
 * Aliases are stored lowercase for case-insensitive matching.
 * Coordinates use equirectangular projection (lat/lng degrees).
 */
export const COUNTRIES = [
  { name: 'Afghanistan', lat: 33.93, lng: 67.71, aliases: ['af', 'afg'] },
  { name: 'Albania', lat: 41.15, lng: 20.17, aliases: ['al', 'alb'] },
  { name: 'Algeria', lat: 28.03, lng: 1.66, aliases: ['dz', 'alg'] },
  { name: 'Andorra', lat: 42.55, lng: 1.60, aliases: ['ad'] },
  { name: 'Angola', lat: -11.20, lng: 17.87, aliases: ['ao', 'ang'] },
  { name: 'Antigua and Barbuda', lat: 17.06, lng: -61.80, aliases: ['antigua', 'barbuda', 'ag'] },
  { name: 'Argentina', lat: -38.42, lng: -63.62, aliases: ['ar', 'arg'] },
  { name: 'Armenia', lat: 40.07, lng: 45.04, aliases: ['am', 'arm'] },
  { name: 'Australia', lat: -25.27, lng: 133.78, aliases: ['au', 'aus', 'oz', 'aussie'] },
  { name: 'Austria', lat: 47.52, lng: 14.55, aliases: ['at', 'aut', 'österreich', 'oesterreich'] },
  { name: 'Azerbaijan', lat: 40.14, lng: 47.58, aliases: ['az', 'aze'] },
  { name: 'Bahamas', lat: 25.03, lng: -77.40, aliases: ['bs', 'bah', 'the bahamas'] },
  { name: 'Bahrain', lat: 26.00, lng: 50.55, aliases: ['bh', 'bhr'] },
  { name: 'Bangladesh', lat: 23.68, lng: 90.36, aliases: ['bd', 'ban'] },
  { name: 'Barbados', lat: 13.19, lng: -59.54, aliases: ['bb', 'brb'] },
  { name: 'Belarus', lat: 53.71, lng: 27.95, aliases: ['by', 'blr', 'byelorussia'] },
  { name: 'Belgium', lat: 50.50, lng: 4.47, aliases: ['be', 'bel', 'belgique', 'belgië'] },
  { name: 'Belize', lat: 17.19, lng: -88.50, aliases: ['bz', 'blz'] },
  { name: 'Benin', lat: 9.31, lng: 2.32, aliases: ['bj', 'ben'] },
  { name: 'Bhutan', lat: 27.51, lng: 90.43, aliases: ['bt', 'btn'] },
  { name: 'Bolivia', lat: -16.29, lng: -63.59, aliases: ['bo', 'bol'] },
  { name: 'Bosnia and Herzegovina', lat: 43.92, lng: 17.68, aliases: ['ba', 'bih', 'bosnia', 'herzegovina', 'bih'] },
  { name: 'Botswana', lat: -22.33, lng: 24.68, aliases: ['bw', 'bwa'] },
  { name: 'Brazil', lat: -14.24, lng: -51.93, aliases: ['br', 'bra', 'brasil'] },
  { name: 'Brunei', lat: 4.54, lng: 114.73, aliases: ['bn', 'brn', 'brunei darussalam'] },
  { name: 'Bulgaria', lat: 42.73, lng: 25.49, aliases: ['bg', 'bul', 'България'] },
  { name: 'Burkina Faso', lat: 12.36, lng: -1.53, aliases: ['bf', 'bfa'] },
  { name: 'Burundi', lat: -3.37, lng: 29.92, aliases: ['bi', 'bdi'] },
  { name: 'Cabo Verde', lat: 16.00, lng: -24.01, aliases: ['cv', 'cpv', 'cape verde'] },
  { name: 'Cambodia', lat: 12.57, lng: 104.99, aliases: ['kh', 'khm', 'kampuchea'] },
  { name: 'Cameroon', lat: 7.37, lng: 12.35, aliases: ['cm', 'cmr'] },
  { name: 'Canada', lat: 56.13, lng: -106.35, aliases: ['ca', 'can'] },
  { name: 'Central African Republic', lat: 6.61, lng: 20.94, aliases: ['cf', 'caf', 'car', 'central africa'] },
  { name: 'Chad', lat: 15.45, lng: 18.73, aliases: ['td', 'tcd'] },
  { name: 'Chile', lat: -35.68, lng: -71.54, aliases: ['cl', 'chl'] },
  { name: 'China', lat: 35.86, lng: 104.20, aliases: ['cn', 'chn', 'prc', "people's republic of china"] },
  { name: 'Colombia', lat: 4.57, lng: -74.30, aliases: ['co', 'col'] },
  { name: 'Comoros', lat: -11.87, lng: 43.87, aliases: ['km', 'com'] },
  { name: 'Congo', lat: -0.23, lng: 15.83, aliases: ['cg', 'cog', 'republic of the congo', 'republic of congo'] },
  { name: 'Democratic Republic of the Congo', lat: -4.04, lng: 21.76, aliases: ['cd', 'cod', 'drc', 'dr congo', 'zaire', 'democratic republic of congo'] },
  { name: 'Costa Rica', lat: 9.75, lng: -83.75, aliases: ['cr', 'cri'] },
  { name: 'Croatia', lat: 45.10, lng: 15.20, aliases: ['hr', 'hrv', 'hrvatska'] },
  { name: 'Cuba', lat: 21.52, lng: -77.78, aliases: ['cu', 'cub'] },
  { name: 'Cyprus', lat: 35.13, lng: 33.43, aliases: ['cy', 'cyp'] },
  { name: 'Czech Republic', lat: 49.82, lng: 15.47, aliases: ['cz', 'cze', 'czechia', 'czech', 'česká republika'] },
  { name: 'Denmark', lat: 56.26, lng: 9.50, aliases: ['dk', 'dnk', 'danmark'] },
  { name: 'Djibouti', lat: 11.83, lng: 42.59, aliases: ['dj', 'dji'] },
  { name: 'Dominica', lat: 15.41, lng: -61.37, aliases: ['dm', 'dma'] },
  { name: 'Dominican Republic', lat: 18.74, lng: -70.16, aliases: ['do', 'dom', 'dominican'] },
  { name: 'Ecuador', lat: -1.83, lng: -78.18, aliases: ['ec', 'ecu'] },
  { name: 'Egypt', lat: 26.82, lng: 30.80, aliases: ['eg', 'egy', 'مصر'] },
  { name: 'El Salvador', lat: 13.79, lng: -88.90, aliases: ['sv', 'slv', 'salvador'] },
  { name: 'Equatorial Guinea', lat: 1.65, lng: 10.27, aliases: ['gq', 'gnq'] },
  { name: 'Eritrea', lat: 15.18, lng: 39.78, aliases: ['er', 'eri'] },
  { name: 'Estonia', lat: 58.60, lng: 25.01, aliases: ['ee', 'est', 'eesti'] },
  { name: 'Eswatini', lat: -26.52, lng: 31.47, aliases: ['sz', 'swz', 'swaziland'] },
  { name: 'Ethiopia', lat: 9.15, lng: 40.49, aliases: ['et', 'eth'] },
  { name: 'Fiji', lat: -17.71, lng: 178.07, aliases: ['fj', 'fji'] },
  { name: 'Finland', lat: 61.92, lng: 25.75, aliases: ['fi', 'fin', 'suomi'] },
  { name: 'France', lat: 46.23, lng: 2.21, aliases: ['fr', 'fra'] },
  { name: 'Gabon', lat: -0.80, lng: 11.61, aliases: ['ga', 'gab'] },
  { name: 'Gambia', lat: 13.44, lng: -15.31, aliases: ['gm', 'gmb', 'the gambia'] },
  { name: 'Georgia', lat: 42.32, lng: 43.36, aliases: ['ge', 'geo'] },
  { name: 'Germany', lat: 51.17, lng: 10.45, aliases: ['de', 'deu', 'deutschland'] },
  { name: 'Ghana', lat: 7.95, lng: -1.02, aliases: ['gh', 'gha'] },
  { name: 'Greece', lat: 39.07, lng: 21.82, aliases: ['gr', 'grc', 'hellas', 'ελλάδα'] },
  { name: 'Grenada', lat: 12.12, lng: -61.68, aliases: ['gd', 'grd'] },
  { name: 'Guatemala', lat: 15.78, lng: -90.23, aliases: ['gt', 'gtm'] },
  { name: 'Guinea', lat: 9.95, lng: -11.61, aliases: ['gn', 'gin'] },
  { name: 'Guinea-Bissau', lat: 11.80, lng: -15.18, aliases: ['gw', 'gnb'] },
  { name: 'Guyana', lat: 4.86, lng: -58.93, aliases: ['gy', 'guy'] },
  { name: 'Haiti', lat: 18.97, lng: -72.29, aliases: ['ht', 'hti'] },
  { name: 'Honduras', lat: 15.20, lng: -86.24, aliases: ['hn', 'hnd'] },
  { name: 'Hungary', lat: 47.16, lng: 19.50, aliases: ['hu', 'hun', 'magyarország'] },
  { name: 'Iceland', lat: 64.96, lng: -19.02, aliases: ['is', 'isl', 'ísland'] },
  { name: 'India', lat: 20.59, lng: 78.96, aliases: ['in', 'ind', 'bharat'] },
  { name: 'Indonesia', lat: -0.79, lng: 113.92, aliases: ['id', 'idn'] },
  { name: 'Iran', lat: 32.43, lng: 53.69, aliases: ['ir', 'irn', 'persia', 'islamic republic of iran'] },
  { name: 'Iraq', lat: 33.22, lng: 43.68, aliases: ['iq', 'irq'] },
  { name: 'Ireland', lat: 53.41, lng: -8.24, aliases: ['ie', 'irl', 'éire', 'eire'] },
  { name: 'Israel', lat: 31.05, lng: 34.85, aliases: ['il', 'isr'] },
  { name: 'Italy', lat: 41.87, lng: 12.57, aliases: ['it', 'ita', 'italia'] },
  { name: 'Jamaica', lat: 18.11, lng: -77.30, aliases: ['jm', 'jam'] },
  { name: 'Japan', lat: 36.20, lng: 138.25, aliases: ['jp', 'jpn', '日本', 'nihon', 'nippon'] },
  { name: 'Jordan', lat: 30.59, lng: 36.24, aliases: ['jo', 'jor'] },
  { name: 'Kazakhstan', lat: 48.02, lng: 66.92, aliases: ['kz', 'kaz'] },
  { name: 'Kenya', lat: -0.02, lng: 37.91, aliases: ['ke', 'ken'] },
  { name: 'Kiribati', lat: -3.37, lng: -168.73, aliases: ['ki', 'kir'] },
  { name: 'Kuwait', lat: 29.31, lng: 47.48, aliases: ['kw', 'kwt'] },
  { name: 'Kyrgyzstan', lat: 41.20, lng: 74.77, aliases: ['kg', 'kgz', 'kyrgyz'] },
  { name: 'Laos', lat: 19.86, lng: 102.50, aliases: ['la', 'lao', 'lao pdr'] },
  { name: 'Latvia', lat: 56.88, lng: 24.60, aliases: ['lv', 'lva', 'latvija'] },
  { name: 'Lebanon', lat: 33.85, lng: 35.86, aliases: ['lb', 'lbn'] },
  { name: 'Lesotho', lat: -29.61, lng: 28.23, aliases: ['ls', 'lso'] },
  { name: 'Liberia', lat: 6.43, lng: -9.43, aliases: ['lr', 'lbr'] },
  { name: 'Libya', lat: 26.34, lng: 17.23, aliases: ['ly', 'lby'] },
  { name: 'Liechtenstein', lat: 47.17, lng: 9.56, aliases: ['li', 'lie'] },
  { name: 'Lithuania', lat: 55.17, lng: 23.88, aliases: ['lt', 'ltu', 'lietuva'] },
  { name: 'Luxembourg', lat: 49.82, lng: 6.13, aliases: ['lu', 'lux'] },
  { name: 'Madagascar', lat: -18.77, lng: 46.87, aliases: ['mg', 'mdg'] },
  { name: 'Malawi', lat: -13.25, lng: 34.30, aliases: ['mw', 'mwi'] },
  { name: 'Malaysia', lat: 4.21, lng: 108.00, aliases: ['my', 'mys'] },
  { name: 'Maldives', lat: 3.20, lng: 73.22, aliases: ['mv', 'mdv'] },
  { name: 'Mali', lat: 17.57, lng: -3.99, aliases: ['ml', 'mli'] },
  { name: 'Malta', lat: 35.94, lng: 14.38, aliases: ['mt', 'mlt'] },
  { name: 'Marshall Islands', lat: 7.13, lng: 171.18, aliases: ['mh', 'mhl'] },
  { name: 'Mauritania', lat: 21.01, lng: -10.94, aliases: ['mr', 'mrt'] },
  { name: 'Mauritius', lat: -20.35, lng: 57.55, aliases: ['mu', 'mus'] },
  { name: 'Mexico', lat: 23.63, lng: -102.55, aliases: ['mx', 'mex', 'méxico'] },
  { name: 'Micronesia', lat: 7.43, lng: 150.55, aliases: ['fm', 'fsm', 'federated states of micronesia'] },
  { name: 'Moldova', lat: 47.41, lng: 28.37, aliases: ['md', 'mda', 'republic of moldova'] },
  { name: 'Monaco', lat: 43.73, lng: 7.40, aliases: ['mc', 'mco'] },
  { name: 'Mongolia', lat: 46.86, lng: 103.85, aliases: ['mn', 'mng'] },
  { name: 'Montenegro', lat: 42.71, lng: 19.37, aliases: ['me', 'mne'] },
  { name: 'Morocco', lat: 31.79, lng: -7.09, aliases: ['ma', 'mar', 'maroc', 'المغرب'] },
  { name: 'Mozambique', lat: -18.67, lng: 35.53, aliases: ['mz', 'moz'] },
  { name: 'Myanmar', lat: 21.92, lng: 95.96, aliases: ['mm', 'mmr', 'burma'] },
  { name: 'Namibia', lat: -22.96, lng: 18.49, aliases: ['na', 'nam'] },
  { name: 'Nauru', lat: -0.52, lng: 166.93, aliases: ['nr', 'nru'] },
  { name: 'Nepal', lat: 28.39, lng: 84.12, aliases: ['np', 'npl'] },
  { name: 'Netherlands', lat: 52.13, lng: 5.29, aliases: ['nl', 'nld', 'holland', 'nederland'] },
  { name: 'New Zealand', lat: -40.90, lng: 174.89, aliases: ['nz', 'nzl', 'nz', 'aotearoa'] },
  { name: 'Nicaragua', lat: 12.87, lng: -85.21, aliases: ['ni', 'nic'] },
  { name: 'Niger', lat: 17.61, lng: 8.08, aliases: ['ne', 'ner'] },
  { name: 'Nigeria', lat: 9.08, lng: 8.68, aliases: ['ng', 'nga'] },
  { name: 'North Korea', lat: 40.34, lng: 127.51, aliases: ['kp', 'prk', 'dprk'] },
  { name: 'North Macedonia', lat: 41.61, lng: 21.75, aliases: ['mk', 'mkd', 'macedonia'] },
  { name: 'Norway', lat: 60.47, lng: 8.47, aliases: ['no', 'nor', 'norge'] },
  { name: 'Oman', lat: 21.00, lng: 57.00, aliases: ['om', 'omn'] },
  { name: 'Pakistan', lat: 30.38, lng: 69.35, aliases: ['pk', 'pak'] },
  { name: 'Palau', lat: 7.51, lng: 134.58, aliases: ['pw', 'plw'] },
  { name: 'Palestine', lat: 31.95, lng: 35.23, aliases: ['ps', 'pse', 'palestinian territories'] },
  { name: 'Panama', lat: 8.54, lng: -80.78, aliases: ['pa', 'pan'] },
  { name: 'Papua New Guinea', lat: -6.31, lng: 143.96, aliases: ['pg', 'png', 'papua'] },
  { name: 'Paraguay', lat: -23.44, lng: -58.44, aliases: ['py', 'pry'] },
  { name: 'Peru', lat: -9.19, lng: -75.02, aliases: ['pe', 'per'] },
  { name: 'Philippines', lat: 12.88, lng: 121.77, aliases: ['ph', 'phl', 'pilipinas'] },
  { name: 'Poland', lat: 51.92, lng: 19.15, aliases: ['pl', 'pol', 'polska'] },
  { name: 'Portugal', lat: 39.40, lng: -8.22, aliases: ['pt', 'prt'] },
  { name: 'Qatar', lat: 25.35, lng: 51.18, aliases: ['qa', 'qat'] },
  { name: 'Romania', lat: 45.94, lng: 24.97, aliases: ['ro', 'rou', 'românia'] },
  { name: 'Russia', lat: 61.52, lng: 105.32, aliases: ['ru', 'rus', 'russian federation', 'россия'] },
  { name: 'Rwanda', lat: -1.94, lng: 29.87, aliases: ['rw', 'rwa'] },
  { name: 'Saint Kitts and Nevis', lat: 17.36, lng: -62.78, aliases: ['kn', 'kna', 'st kitts', 'saint kitts'] },
  { name: 'Saint Lucia', lat: 13.91, lng: -60.98, aliases: ['lc', 'lca', 'st lucia'] },
  { name: 'Saint Vincent and the Grenadines', lat: 12.98, lng: -61.29, aliases: ['vc', 'vct', 'saint vincent', 'st vincent'] },
  { name: 'Samoa', lat: -13.76, lng: -172.10, aliases: ['ws', 'wsm'] },
  { name: 'San Marino', lat: 43.94, lng: 12.46, aliases: ['sm', 'smr'] },
  { name: 'Saudi Arabia', lat: 23.89, lng: 45.08, aliases: ['sa', 'sau', 'ksa', 'saudi'] },
  { name: 'Senegal', lat: 14.50, lng: -14.45, aliases: ['sn', 'sen'] },
  { name: 'Serbia', lat: 44.02, lng: 21.01, aliases: ['rs', 'srb', 'srbija'] },
  { name: 'Seychelles', lat: -4.68, lng: 55.49, aliases: ['sc', 'syc'] },
  { name: 'Sierra Leone', lat: 8.46, lng: -11.78, aliases: ['sl', 'sle'] },
  { name: 'Singapore', lat: 1.35, lng: 103.82, aliases: ['sg', 'sgp'] },
  { name: 'Slovakia', lat: 48.67, lng: 19.70, aliases: ['sk', 'svk', 'slovensko'] },
  { name: 'Slovenia', lat: 46.15, lng: 14.99, aliases: ['si', 'svn', 'slovenija'] },
  { name: 'Solomon Islands', lat: -9.65, lng: 160.16, aliases: ['sb', 'slb'] },
  { name: 'Somalia', lat: 5.15, lng: 46.20, aliases: ['so', 'som'] },
  { name: 'South Africa', lat: -30.56, lng: 22.94, aliases: ['za', 'zaf', 'rsa', 'south africa'] },
  { name: 'South Korea', lat: 35.91, lng: 127.77, aliases: ['kr', 'kor', 'korea', 'republic of korea'] },
  { name: 'South Sudan', lat: 6.88, lng: 31.31, aliases: ['ss', 'ssd'] },
  { name: 'Spain', lat: 40.46, lng: -3.75, aliases: ['es', 'esp', 'españa'] },
  { name: 'Sri Lanka', lat: 7.87, lng: 80.77, aliases: ['lk', 'lka', 'ceylon'] },
  { name: 'Sudan', lat: 12.86, lng: 30.22, aliases: ['sd', 'sdn'] },
  { name: 'Suriname', lat: 3.92, lng: -56.03, aliases: ['sr', 'sur'] },
  { name: 'Sweden', lat: 60.13, lng: 18.64, aliases: ['se', 'swe', 'sverige'] },
  { name: 'Switzerland', lat: 46.82, lng: 8.23, aliases: ['ch', 'che', 'schweiz', 'suisse', 'svizzera'] },
  { name: 'Syria', lat: 34.80, lng: 38.99, aliases: ['sy', 'syr', 'syrian arab republic'] },
  { name: 'Taiwan', lat: 23.70, lng: 120.96, aliases: ['tw', 'twn', 'roc', 'republic of china'] },
  { name: 'Tajikistan', lat: 38.86, lng: 71.28, aliases: ['tj', 'tjk'] },
  { name: 'Tanzania', lat: -6.37, lng: 34.89, aliases: ['tz', 'tza', 'united republic of tanzania'] },
  { name: 'Thailand', lat: 15.87, lng: 100.99, aliases: ['th', 'tha', 'ประเทศไทย'] },
  { name: 'Timor-Leste', lat: -8.87, lng: 125.73, aliases: ['tl', 'tls', 'east timor', 'timor leste'] },
  { name: 'Togo', lat: 8.62, lng: 0.82, aliases: ['tg', 'tgo'] },
  { name: 'Tonga', lat: -21.18, lng: -175.20, aliases: ['to', 'ton'] },
  { name: 'Trinidad and Tobago', lat: 10.69, lng: -61.22, aliases: ['tt', 'tto', 'trinidad', 'tobago'] },
  { name: 'Tunisia', lat: 33.89, lng: 9.54, aliases: ['tn', 'tun'] },
  { name: 'Turkey', lat: 38.96, lng: 35.24, aliases: ['tr', 'tur', 'türkiye', 'turkiye'] },
  { name: 'Turkmenistan', lat: 38.97, lng: 59.56, aliases: ['tm', 'tkm'] },
  { name: 'Tuvalu', lat: -7.11, lng: 179.09, aliases: ['tv', 'tuv'] },
  { name: 'Uganda', lat: 1.37, lng: 32.29, aliases: ['ug', 'uga'] },
  { name: 'Ukraine', lat: 48.38, lng: 31.17, aliases: ['ua', 'ukr', 'україна'] },
  { name: 'United Arab Emirates', lat: 23.42, lng: 53.85, aliases: ['ae', 'are', 'uae', 'emirates'] },
  { name: 'United Kingdom', lat: 55.38, lng: -3.44, aliases: ['gb', 'gbr', 'uk', 'great britain', 'britain', 'england', 'scotland', 'wales'] },
  { name: 'United States', lat: 37.09, lng: -95.71, aliases: ['us', 'usa', 'united states of america', 'america', 'u.s.a.', 'u.s.', 'the us', 'the usa'] },
  { name: 'Uruguay', lat: -32.52, lng: -55.77, aliases: ['uy', 'ury'] },
  { name: 'Uzbekistan', lat: 41.38, lng: 64.59, aliases: ['uz', 'uzb'] },
  { name: 'Vanuatu', lat: -15.38, lng: 166.96, aliases: ['vu', 'vut'] },
  { name: 'Vatican City', lat: 41.90, lng: 12.45, aliases: ['va', 'vat', 'holy see'] },
  { name: 'Venezuela', lat: 6.42, lng: -66.59, aliases: ['ve', 'ven'] },
  { name: 'Vietnam', lat: 14.06, lng: 108.28, aliases: ['vn', 'vnm', 'việt nam', 'viet nam'] },
  { name: 'Yemen', lat: 15.55, lng: 48.52, aliases: ['ye', 'yem'] },
  { name: 'Zambia', lat: -13.13, lng: 27.85, aliases: ['zm', 'zmb'] },
  { name: 'Zimbabwe', lat: -19.02, lng: 29.15, aliases: ['zw', 'zwe'] },
];

// Build a flat lookup map: lowercase alias/name → country object
const _lookup = new Map();
for (const country of COUNTRIES) {
  _lookup.set(country.name.toLowerCase(), country);
  for (const alias of country.aliases) {
    _lookup.set(alias.toLowerCase(), country);
  }
}

/**
 * Resolve a user-supplied string to a country object.
 * Returns null if no match is found.
 */
export function resolveCountry(input) {
  if (!input || typeof input !== 'string') return null;
  const key = input.trim().toLowerCase();
  return _lookup.get(key) ?? null;
}
